// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHmWheC8ihfJCc-7Bm9TFM5W-Z8prBGc',
    appId: '1:61729669377:web:ad3742302f3abe2cc71b00',
    messagingSenderId: '61729669377',
    projectId: 'project-7561f',
    authDomain: 'project-7561f.firebaseapp.com',
    storageBucket: 'project-7561f.appspot.com',
    measurementId: 'G-KFWL80K40P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6V8wDQ_OLfxK7p04csAbOUlTwUGKK9FA',
    appId: '1:61729669377:android:f380927bd05e570bc71b00',
    messagingSenderId: '61729669377',
    projectId: 'project-7561f',
    storageBucket: 'project-7561f.appspot.com',
  );
}
